name: Build

concurrency:
  group: "build"
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2
        with:
          path: "src"

      - name: Checkout builds branch
        uses: actions/checkout@v4.2.2
        with:
          ref: "builds"
          path: "builds"
          token: ${{ secrets.BOT }}

      - name: Clean old builds
        run: |
          rm -f $GITHUB_WORKSPACE/builds/*.cs3
          rm -f $GITHUB_WORKSPACE/builds/*.jar

      - name: Setup JDK 17
        uses: actions/setup-java@v4.6.0
        with:
          distribution: "adopt"
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.2

      - name: Build Plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make makePluginsJson
          ./gradlew ensureJarCompatibility
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds || true
          cp **/build/*.jar $GITHUB_WORKSPACE/builds || true
          cp build/plugins.json $GITHUB_WORKSPACE/builds

      - name: Push builds
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git remote set-url origin https://x-access-token:${{ secrets.BOT }}@github.com/mozzaru/cloude-strm.git
          git checkout builds || git checkout -b builds
          git add .
          git commit -m "Build $GITHUB_SHA" || echo "Nothing to commit"
          git push origin builds --force
          