# This tool was written by @keyiflerolsun for @KekikAkademi.
name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
      - "**/*.jpg"
      - "**/*.png"
      - "**/*.py"

jobs:
  CloudStreamCompiler:
    runs-on: ubuntu-latest
    steps:
      - name: Check out 'src' Repository
        uses: actions/checkout@v4.2.2
        with:
          path: "src"

      - name: Check out 'build' Repository
        uses: actions/checkout@v4.2.2
        with:
          ref: "builds"
          path: "builds"
          token: ${{ secrets.BOT }}

      - name: Clean Old Builds
        run: rm $GITHUB_WORKSPACE/builds/*.cs3 || true

      - name: Set up JDK 23
        uses: actions/setup-java@v4.6.0
        with:
          distribution: adopt
          java-version: 23

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3.2.2

      - name: Build Plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make makePluginsJson --stacktrace --info
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds
          cp build/plugins.json $GITHUB_WORKSPACE/builds

      - name: Push builds
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git remote set-url origin https://x-access-token:${{ secrets.BOT }}@github.com/mozzaru/cloude-strm.git
          git checkout builds || git checkout -b builds
          git add .
          git commit -m "Build $GITHUB_SHA" || echo "Nothing to commit"
          git push origin builds --force
          