name: Build

# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches:
      # choose your default branch
      - master
      - main
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          path: "src"

      - name: Checkout repo
        uses: actions/checkout@v4.2.2
        with:
          ref: "repo"
          path: "repo"

      - name: Clean old repo
        run: |
          rm $GITHUB_WORKSPACE/repo/*.cs3 || true
          rm $GITHUB_WORKSPACE/repo/*.jar || true

      - name: Setup JDK 17
        uses: actions/setup-java@v4.6.0
        with:
          distribution: "adopt"
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.2

      - name: Build Plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make makePluginsJson
          ./gradlew ensureJarCompatibility
          cp **/build/*.cs3 $GITHUB_WORKSPACE/repo
          cp **/build/*.jar $GITHUB_WORKSPACE/repo
          cp build/plugins.json $GITHUB_WORKSPACE/repo

      - name: Push repo
        run: |
          cd $GITHUB_WORKSPACE/repo
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit --amend -m "Build $GITHUB_SHA" || exit 0   # do not error if nothing to commit
          git push --force
